name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install tools
        run: pip install build twine

      - name: Build
        run: |
          python -m build
          echo "[disutils]"                       > ~/.pypirc
          echo "index-servers=pypi"              >> ~/.pypirc
          echo "[pypi]"                          >> ~/.pypirc
          echo "username=__token__"              >> ~/.pypirc
          echo "password=${{ secrets.SECRETS }}" >> ~/.pypirc
          cat ~/.pypirc
          twine upload dist/* --config-file ~/.pypirc --skip-existing
      #- name: Upload
      #  uses: yaananth/twine-upload@v1
      #  env:
      #    RUNNER: ${{ toJson(runner) }}
      #    SECRETS: ${{ toJson(secrets) }}

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ./dist/pyAutoMR-v*-py3-none-any.whl
